<<<<<<< Updated upstream
<<<<<<< Updated upstream
title: Flow справка Граждан
=======
title: Flow справка для граждан
>>>>>>> Stashed changes
=======
title: Flow справка для граждан
>>>>>>> Stashed changes
optionalCategoryIndex: true
supportedLanguages: []
properties: []
link:
  name: Flow_TSU_GR_help
  pathname: github.com/Smile-Tech-Study/Flow_TSU_GR_help/main/-
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  lastVisited: >-
    github.com/Smile-Tech-Study/Flow_TSU_GR_help/main/-/voprosy/postanovlenie-ot-7-marta-2025-goda-291
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
  logo: null
  title: Flow_TSU_GR_help
  query: {}
  group: null
  code: ""
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: Flow_TSU_GR_help
repositoryName: Flow_TSU_GR_help
sourceName: github.com
userInfo:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  mail: l.nikitina23@yandex.com
  name: nickeylaa
  id: l.nikitina23@yandex.com
=======
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
>>>>>>> Stashed changes
=======
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
>>>>>>> Stashed changes
logo: Logo 10 1.svg
logo_dark: Logo 10 1.svg
